<?php

namespace redcapuzgent\Randapidao\model;

class ChangeTargetAction extends RandApiAction
{
    /**
     * RandomizeRecordAction constructor.
     * @param ChangeTargetParameters $parameters
     * @param string $token
     */
    public function __construct(ChangeTargetParameters $parameters, string $token)
    {
        parent::__construct("changeTarget", $token, $parameters);
    }

    /**
     * @return ChangeTargetParameters
     */
    public function getParameters(): ChangeTargetParameters
    {
        return parent::getParameters(); // TODO: Change the autogenerated stub
    }
}