<?php

namespace redcapuzgent\Randapidao\model;

class ChangeSourcesAction extends RandApiAction
{
    /**
     * RandomizeRecordAction constructor.
     * @param ChangeSourcesParameters $parameters
     * @param string $token
     */
    public function __construct(ChangeSourcesParameters $parameters, string $token)
    {
        parent::__construct("changeSources", $token, $parameters);
    }

    /**
     * @return ChangeSourcesParameters
     */
    public function getParameters(): ChangeSourcesParameters
    {
        return parent::getParameters(); // TODO: Change the autogenerated stub
    }
}