<?php

namespace redcapuzgent\Randapidao\model;

class RandomizeRecordAction extends RandApiAction
{
    /**
     * RandomizeRecordAction constructor.
     * @param RandomizeRecordParameters $parameters
     * @param string $token
     */
    public function __construct(RandomizeRecordParameters $parameters, string $token)
    {
        parent::__construct("randomizeRecord", $token, $parameters);
    }

    /**
     * @return RandomizeRecordParameters
     */
    public function getParameters(): RandomizeRecordParameters
    {
        return parent::getParameters(); // TODO: Change the autogenerated stub
    }
}